// Code generated by INKWASM BUILD; DO NOT EDIT
#include "textflag.h"

TEXT ·newUsage(SB), NOSPLIT, $0
	JMP ·_newUsage(SB)
	RET

TEXT ·copyArray(SB), NOSPLIT, $0
	JMP ·_copyArray(SB)
	RET

TEXT ·getWebCryptoAPI(SB), NOSPLIT, $0
	JMP ·_getWebCryptoAPI(SB)
	RET

TEXT ·importKey(SB), NOSPLIT, $0
	JMP ·_importKey(SB)
	RET

TEXT ·deriveKey(SB), NOSPLIT, $0
	JMP ·_deriveKey(SB)
	RET

TEXT ·exportKey(SB), NOSPLIT, $0
	JMP ·_exportKey(SB)
	RET
