// Code generated by INKWASM BUILD; DO NOT EDIT
(() => {
	if (globalThis.inkwasm === undefined) {
		globalThis.inkwasm = {Load: {}};
	}

	globalThis.inkwasm.Load.importKeyOptions = function(go, sp, offset) {
		sp += offset
		return {
			"_":globalThis.inkwasm.Load.Uint64(go, sp, 0),
			"name":globalThis.inkwasm.Load.String(go, sp, 8),

		}
	}

	globalThis.inkwasm.Load.deriveKeyOptions = function(go, sp, offset) {
		sp += offset
		return {
			"_":globalThis.inkwasm.Load.Uint64(go, sp, 0),
			"name":globalThis.inkwasm.Load.String(go, sp, 8),
			"salt":globalThis.inkwasm.Load.InkwasmObject(go, sp, 24),
			"iterations":globalThis.inkwasm.Load.Int32(go, sp, 40),
			"hash":globalThis.inkwasm.Load.String(go, sp, 48),

		}
	}

	globalThis.inkwasm.Load.deriveKeyMode = function(go, sp, offset) {
		sp += offset
		return {
			"_":globalThis.inkwasm.Load.Uint64(go, sp, 0),
			"name":globalThis.inkwasm.Load.String(go, sp, 8),
			"length":globalThis.inkwasm.Load.Int32(go, sp, 24),

		}
	}

})();
// Code generated by INKWASM BUILD; DO NOT EDIT
(() => {
	Object.assign(go.importObject.go, {

		"github.com/inkeliz/gowasm-pbkdf2.__newUsage": (sp) => {
			let r = new globalThis.Array(globalThis.inkwasm.Load.String(go, sp, 8),globalThis.inkwasm.Load.String(go, sp, 24))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 40, r)
		},

		"github.com/inkeliz/gowasm-pbkdf2.__copyArray": (sp) => {
			let r = new globalThis.Uint8Array(globalThis.inkwasm.Load.Slice(go, sp, 8, globalThis.inkwasm.Load.ArrayByte))
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 32, r)
		},

		"github.com/inkeliz/gowasm-pbkdf2.__getWebCryptoAPI": (sp) => {
			let r = globalThis.crypto.subtle
			sp = go._inst.exports.getsp() >>> 0
			globalThis.inkwasm.Set.InkwasmObject(go, sp, 8, r)
		},

		"github.com/inkeliz/gowasm-pbkdf2.__importKey": (sp) => {
			try {
				let r = globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).importKey(globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.InkwasmObject(go, sp, 40),globalThis.inkwasm.Load.importKeyOptions(go, sp, 56),globalThis.inkwasm.Load.Bool(go, sp, 80),globalThis.inkwasm.Load.InkwasmObject(go, sp, 88))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.InkwasmObject(go, sp, 104, r)
				globalThis.inkwasm.Set.Bool(go, sp, 120, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 120, false)
			}
		},

		"github.com/inkeliz/gowasm-pbkdf2.__deriveKey": (sp) => {
			try {
				let r = globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).deriveKey(globalThis.inkwasm.Load.deriveKeyOptions(go, sp, 24),globalThis.inkwasm.Load.InkwasmObject(go, sp, 88),globalThis.inkwasm.Load.deriveKeyMode(go, sp, 104),globalThis.inkwasm.Load.Bool(go, sp, 136),globalThis.inkwasm.Load.InkwasmObject(go, sp, 144))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.InkwasmObject(go, sp, 160, r)
				globalThis.inkwasm.Set.Bool(go, sp, 176, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 176, false)
			}
		},

		"github.com/inkeliz/gowasm-pbkdf2.__exportKey": (sp) => {
			try {
				let r = globalThis.inkwasm.Load.InkwasmObject(go, sp, 8).exportKey(globalThis.inkwasm.Load.String(go, sp, 24),globalThis.inkwasm.Load.InkwasmObject(go, sp, 40))
				sp = go._inst.exports.getsp() >>> 0
				globalThis.inkwasm.Set.InkwasmObject(go, sp, 56, r)
				globalThis.inkwasm.Set.Bool(go, sp, 72, true)
						}catch(e){
				console.log(e)
				globalThis.inkwasm.Set.Bool(go, sp, 72, false)
			}
		},

	})
})();
